version: "3.9"
services:

    #PHP Service Laravel Application
    app:
        build:
          args:
              user: ${DOCKER_USERNAME}
              uid: ${DOCKER_USER_ID}
          context: ./docker/php
          dockerfile: Dockerfile
        container_name: ${APP_NAME}-app
        restart: unless-stopped
        working_dir: /var/www/
        tty: true
        volumes:
          - ./:/var/www
          - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
          - ${APP_NAME}

    #MySQL Service
    db:
      image: mysql:8.1.0
      container_name: ${APP_NAME}-db
      restart: always
      environment:
        - MYSQL_DB=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      volumes:
        - ./docker/mysql:/var/lib/mysql
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 10s
        retries: 5
      networks:
          - ${APP_NAME}

    #PhpMyAdmin Service
    pma:
      image: phpmyadmin:latest
      container_name: ${APP_NAME}-pma
      depends_on:
        db:
          condition: service_healthy
      links:
        - db
      ports:
        - "${DOCKER_PMA_PORT}:80"
      environment:
        - 'PMA_HOST:${DB_HOST}'
        - 'PMA_USER:${DB_USERNAME}'
        - 'PMA_PASSWORD:${DB_PASSWORD}'
      restart: always
      networks:
        - ${APP_NAME}

    #Nginx Service
    nginx:
        image: nginx:1.17-alpine
        container_name: ${APP_NAME}-nginx
        restart: unless-stopped
        tty: true
        ports:
          - "${DOCKER_NGINX_PORT}:80"
        volumes:
          - ./:/var/www
          - ./docker/nginx:/etc/nginx/conf.d
        networks:
          - ${APP_NAME}

networks:
    ToDo:
        driver: bridge
